#!/bin/bash

addr=$(aws ec2 describe-instances \
    --filters "Name=tag:Name,Values=$1" \
    --output json \
    --query 'Reservations[0].Instances[0].PublicDnsName')

addr=$(echo $addr | tr -d '"')
echo $addr
