#!/bin/bash

RESTART_CHANNEL_ID=$1

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ $USER == 'ubuntu' ]; then
	git pull origin master
	npm install .
else
	echo "Not on prod!"
fi

ts=$(date +%s)
pkill -f "node bot.js"
node bot.js $RESTART_CHANNEL_ID > logs/platbot-$ts.log 2>&1 &

echo "Plat-bot running."
